linters:
    enable-all: true
    disable:
        - tagliatelle
        - depguard
        - gofumpt
        - gochecknoglobals
        - nonamedreturns
        - wrapcheck
        - exhaustruct
        - goerr113
        - dupl
issues:
    exclude-rules:
        - path: _test\.go
          linters:
              - funlen
              - exhaustivestruct
