services:
  example-app:
    build: .
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - JWT_KEY=${JWT_KEY}
      - POSTGRES_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgre:5432/${POSTGRES_DB}
    depends_on:
      - postgre
  postgre:
    image: postgres:15.4-alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
