services:
  example-app:
    build: .
    ports:
      - "8000:8000"
  postgre:
    image: postgres:15.4-alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
