apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:15.4-alpine3.18
                  imagePullPolicy: "IfNotPresent"
                  ports:
                      - containerPort: 5432
                  envFrom:
                      - configMapRef:
                            name: postgres-config
                  volumeMounts:
                      - mountPath: /var/lib/postgresql/data
                        name: postgredb
                  resources:
                      requests:
                          memory: "64Mi"
                          cpu: "250m"
                      limits:
                          cpu: 500m
                          memory: "128Mi"
            nodeSelector:
                polls-app: db
            volumes:
                - name: postgredb
                  persistentVolumeClaim:
                      claimName: postgres-pv-claim
